version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: moyzavod
      POSTGRES_PASSWORD: somesecretpassword
    volumes:
      - db:/var/lib/postgresql/data
  app:
    image: ghcr.io/Terisback/moyzavod:${TAG}
    env_file:
      - ${TAG}.env
    ports:
      - 443:443
  mail:
    image: bytemark/smtp
    restart: always

volumes:
  db:
